import os
import json
from dotenv import load_dotenv
from openai import OpenAI

# 1. Load environment variables and initialize the client
load_dotenv()
api_key = os.getenv("DEEPSEEK_API_KEY")

if not api_key:
    raise ValueError("DEEPSEEK_API_KEY not found. Please check your .env file.")

# DeepSeek is compatible with the OpenAI SDK; we just change the base URL
client = OpenAI(
    api_key=api_key,
    base_url="https://api.deepseek.com"
)

def evaluate_page_with_llm(markdown_text, url):
    """
    Sends the page content to DeepSeek and forces a strict JSON response
    evaluating both the company context and AI footprint.
    """
    system_prompt = """
    You are an expert corporate analyst. Your job is to read the provided Markdown text from a company's website and extract two specific pieces of information. 
    
    You must respond ONLY in valid JSON format with the following keys:
    {
        "is_company_context_go": true/false,
        "company_summary": "If true, provide a summary of what the company does in EXACTLY 1 to 5 sentences. If false, return null.",
        "is_ai_footprint_go": true/false,
        "ai_summary": "If true, provide a summary of their artificial intelligence initiatives in EXACTLY 1 to 5 sentences. If false, return null."
    }
    
    Do not hallucinate. If the information is not present in the text, mark the respective boolean as false and return null. Do not include markdown formatting like ```json in your response.
    """

    user_prompt = f"URL: {url}\n\nWebsite Content:\n{markdown_text}"

    try:
        # Utilizing deepseek-v4-flash for the analysis context window
        response = client.chat.completions.create(
            model="deepseek-v4-flash",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            response_format={"type": "json_object"}, 
            temperature=0.1 # Keep it low for analytical consistency
        )
        
        # Parse the JSON string returned by the LLM
        return json.loads(response.choices[0].message.content)
        
    except Exception as e:
        print(f"  [!] Error calling DeepSeek API: {e}")
        return None

def main(domain_folder):
    # Dynamically maps to the prefix-free file name generated by 01.0
    index_path = os.path.join(domain_folder, 'meaningful_urls.json')
    if not os.path.exists(index_path):
        print(f"Error: Could not find {index_path}. Did you run Script 01.0?")
        return
        
    # Load the URLs to scan
    with open(index_path, 'r', encoding='utf-8') as f:
        pages_to_scan = json.load(f)
        
    print(f"\nFound {len(pages_to_scan)} pages to evaluate via DeepSeek...")
    
    final_insights = []
    
    # Loop through the local Markdown files and send to DeepSeek
    for page in pages_to_scan:
        url = page['url']
        md_filepath = page['local_file']
        
        print(f"\nEvaluating: {url}")
        
        if not os.path.exists(md_filepath):
            print(f"  [!] Missing local file: {md_filepath}. Skipping.")
            continue
            
        with open(md_filepath, 'r', encoding='utf-8') as f:
            markdown_text = f.read()
            
        # Call the LLM
        analysis = evaluate_page_with_llm(markdown_text, url)
        
        if analysis:
            # Append the URL to the LLM's JSON response for our records
            analysis['url'] = url
            final_insights.append(analysis)
            
            # Print a quick status to the console
            company_status = "GO" if analysis.get('is_company_context_go') else "NO-GO"
            ai_status = "GO" if analysis.get('is_ai_footprint_go') else "NO-GO"
            print(f"  [+] Context: {company_status} | AI Footprint: {ai_status}")

    # Save the final aggregate report prefix-free
    output_path = os.path.join(domain_folder, 'llm_insights.json')
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(final_insights, f, indent=4)
        
    print(f"\nEvaluation complete! Final insights saved to: {output_path}")

if __name__ == "__main__":
    if os.path.exists("config.json"):
        with open("config.json", "r", encoding="utf-8") as f:
            config = json.load(f)
        
        target_folder = config.get("domain_folder")
        print(f"[+] Automating page evaluation for folder: {target_folder}")
        main(target_folder)
    else:
        print("Error: config.json not found. Run 00_run_pipeline.py first.")